#!/usr/bin/env bash

# get versions from master
master=https://github.com/NixOS/nixpkgs/archive/master.tar.gz
export NIX_PATH=nixpkgs=$master

getUrl() {
  nix eval --json "((import <nixpkgs> {}).$1.urls)" | jq -r '.[0][0]'
}

download() {
  nix-build '<nixpkgs>' -A "$1"
}

cache() {
  nix copy "$1" --to s3://cstrahan-nix-cache
}

#-------------------------------------------------------------------------------

echo "Fetching chrome . . ."

# Make sure the download dir exists
downloadDir=$HOME/Downloads/chrome
mkdir -p $downloadDir

for attr in main binary; do
  url=$(getUrl chromium.upstream-info.$attr)
  file=$(basename "$url")
  if [ ! -e "$downloadDir/$file" ]; then
    echo $"Downloading $file . . ."
    path=$(download chromium.upstream-info.$attr)
    cp --no-preserve=mode,ownership "$path" "$downloadDir/$file"
    cache "$path"
  fi
done

#-------------------------------------------------------------------------------

echo "Fetching spotify . . ."

# Make sure the download dir exists
downloadDir=$HOME/Downloads/spotify
mkdir -p $downloadDir

url=$(getUrl spotify.src)
file=$(basename "$url")
if [ ! -e "$downloadDir/$file" ]; then
  echo $"Downloading $file . . ."
  path=$(download spotify.src)
  cp --no-preserve=mode,ownership "$path" "$downloadDir/$file"
  cache "$path"
fi
