# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  boot.initrd.luks.devices = [
    {
      name = "nixos";
      device = "/dev/disk/by-uuid/d0dee3bf-3a1a-4a94-bc0d-2d2d0d5a77d1";
      allowDiscards = true;
    }
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/28f2cdef-f8de-4ed5-9d42-4269fc2edc2a";
      fsType = "btrfs";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/67E3-17ED";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = 8;
}
