#!/bin/sh

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

for f in *.nix; do
  name=$(basename $f)
  if [[ $name != "hardware-configuration.nix" ]]; then
    cp $f /etc/nixos/$name -v
  fi
done
